# Generated by Django 4.1.6 on 2023-03-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateBith',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
