# Generated by Django 4.1.6 on 2023-03-05 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_datebith'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usertype', verbose_name='Тип пользователя'),
        ),
    ]
