# Generated by Django 4.1.6 on 2023-03-06 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_program_department_program_department'),
        ('users', '0006_alter_customeruser_customer_alter_customeruser_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='post',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='booknumber',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Номер зачетки'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.group', verbose_name='Группа'),
        ),
    ]
