# Generated by Django 4.1.6 on 2023-03-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_usertype_delete_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='dateBith',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
