# Generated by Django 4.1.6 on 2023-12-07 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_datebith'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255, verbose_name='Наименование учебного заведения')),
                ('post', models.CharField(max_length=255, verbose_name='Должность или текущий статус')),
                ('department', models.CharField(max_length=255, verbose_name='Факультет / подразделение')),
                ('cathedra', models.CharField(max_length=255, verbose_name='Кафедра')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профиль пользователя',
            },
        ),
    ]
