# Generated by Django 4.1.6 on 2023-02-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepthTaskState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Глубина постановки задачи',
                'verbose_name_plural': 'Глубина постановки задачи',
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделение'},
        ),
        migrations.RemoveField(
            model_name='internalapplication',
            name='depthTask',
        ),
        migrations.AlterField(
            model_name='department',
            name='head_fio',
            field=models.CharField(max_length=150, verbose_name='ФИО руководителя'),
        ),
        migrations.AddField(
            model_name='internalapplication',
            name='depthTaskState',
            field=models.ManyToManyField(related_name='internalApp_depthTaskState', to='main.depthtaskstate', verbose_name='Глубина постановки задачи'),
        ),
    ]
