# Generated by Django 4.1.6 on 2023-02-15 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_depthtaskstate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name_person',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
    ]
