# Generated by Django 4.1.6 on 2023-02-15 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customer_name_person_alter_customer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customertype',
            options={'verbose_name': 'Тип заказчика', 'verbose_name_plural': 'Тип заказчика'},
        ),
        migrations.AlterField(
            model_name='applicationauthorityprocessing',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.applicationauthority', verbose_name='Внутрянняя заявка'),
        ),
    ]
