# Generated by Django 4.1.6 on 2023-02-28 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_disciplines_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationauthority',
            old_name='programm',
            new_name='program',
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department', verbose_name='Ответственное подразделение')),
                ('eduLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.edulevel', verbose_name='Уровень образования')),
            ],
            options={
                'verbose_name': 'Направление подготовки',
                'verbose_name_plural': 'Направления подготовки',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.program', verbose_name='Направление подготовки'),
            preserve_default=False,
        ),
    ]
