# Generated by Django 4.1.6 on 2023-02-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_programm_applicationauthority_program_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationauthorityprocessing',
            name='group',
        ),
        migrations.RemoveField(
            model_name='internalapplicationprocessing',
            name='group',
        ),
        migrations.RemoveField(
            model_name='packagerequestprocessing',
            name='group',
        ),
    ]
