# Generated by Django 4.1.6 on 2023-03-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_applicationauthorityprocessing_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='department',
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ManyToManyField(related_name='program_department', to='main.department', verbose_name='Ответственное подразделение'),
        ),
    ]
