# Generated by Django 4.1.6 on 2023-03-24 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_remove_program_department_program_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationauthority',
            name='authority_fio',
        ),
        migrations.RemoveField(
            model_name='applicationauthority',
            name='authority_post',
        ),
        migrations.RemoveField(
            model_name='applicationauthority',
            name='department_authority',
        ),
        migrations.RemoveField(
            model_name='applicationauthority',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='applicationauthority',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='applicationauthority',
            name='completion_dates',
            field=models.DateField(verbose_name='Сроки завершения работы над задачей'),
        ),
        migrations.AlterField(
            model_name='applicationauthority',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.RemoveField(
            model_name='applicationauthority',
            name='program',
        ),
        migrations.AddField(
            model_name='applicationauthority',
            name='program',
            field=models.ManyToManyField(related_name='applicationAuthority_program', to='main.program', verbose_name='Направления, специальности'),
        ),
    ]
