# Generated by Django 4.1.6 on 2023-03-24 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_remove_applicationauthority_authority_fio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationauthority',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'userType__name': 'Заказчик'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
    ]
