# Generated by Django 4.1.6 on 2023-03-26 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_alter_applicationauthority_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationauthority',
            old_name='goal',
            new_name='purpose',
        ),
        migrations.AlterField(
            model_name='applicationauthority',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
    ]
