# Generated by Django 4.1.6 on 2023-09-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_applicationauthority_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationauthority',
            options={'verbose_name': 'Заявки органов власти', 'verbose_name_plural': 'Заявки органов власти'},
        ),
        migrations.AlterModelOptions(
            name='applicationbuisness',
            options={'verbose_name': 'Заявки от коммерческого сектора', 'verbose_name_plural': 'Заявки от коммерческого сектора'},
        ),
    ]
