# Generated by Django 4.1.6 on 2023-09-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_applicationauthority_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationbuisness',
            old_name='mail',
            new_name='email',
        ),
    ]
