# Generated by Django 4.1.6 on 2023-10-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_customergoal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depthtask',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
    ]
